import type { ExecutionState, StepOutput } from "../models/step-output.js";

export interface ReportInput {
  executionState: ExecutionState;
  stepOutputs: Map<string, StepOutput>;
  workflowName?: string;
  workflowDescription?: string;
  stepNames?: Map<string, string>;
}

export function generateReport(input: ReportInput): string {
  const { executionState, stepOutputs, workflowName, workflowDescription, stepNames } = input;
  const lines: string[] = [];

  // Header
  lines.push(`# ${workflowName ?? "Workflow Report"}`);
  if (workflowDescription) {
    lines.push(workflowDescription);
  }

  // Status
  if (executionState.status === "failed" && executionState.failed_step) {
    const failedName = stepNames?.get(executionState.failed_step) ?? executionState.failed_step;
    lines.push(`**Status**: Failed at step "${failedName}"`);
  } else {
    lines.push("**Status**: Completed");
  }

  lines.push(`**Started**: ${executionState.started_at}`);

  // Step count
  const completedCount = executionState.completed_steps.length;
  const totalCount = stepOutputs.size || completedCount;
  lines.push(`**Steps**: ${completedCount}/${totalCount} completed`);

  lines.push("");

  // Determine step order: completed_steps then failed_step
  const orderedStepIds = [...executionState.completed_steps];
  if (executionState.failed_step && !orderedStepIds.includes(executionState.failed_step)) {
    orderedStepIds.push(executionState.failed_step);
  }

  // Render each step
  for (let i = 0; i < orderedStepIds.length; i++) {
    const stepId = orderedStepIds[i];
    const stepOutput = stepOutputs.get(stepId);
    const name = stepNames?.get(stepId) ?? stepId;

    lines.push("---");
    lines.push(`## ${name}`);

    if (!stepOutput || stepOutput.output === undefined) {
      if (stepOutput?.error) {
        lines.push(`**Error**: ${stepOutput.error.message}`);
      } else {
        lines.push("No output available.");
      }
    } else {
      const rendered = renderStepOutput(stepOutput.output);
      lines.push(rendered);
    }

    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("*Generated by QACompiler*");
  lines.push("");

  return lines.join("\n");
}

function renderStepOutput(output: Record<string, unknown>): string {
  const type = detectOutputType(output);

  switch (type) {
    case "risk-analysis":
      return renderRiskAnalysis(output);
    case "test-plan":
      return renderTestPlan(output);
    case "test-analysis":
      return renderTestAnalysis(output);
    case "test-design":
      return renderTestDesign(output);
    default:
      return renderJsonFallback(output);
  }
}

type BuiltinType = "risk-analysis" | "test-plan" | "test-analysis" | "test-design" | "unknown";

function detectOutputType(output: Record<string, unknown>): BuiltinType {
  if ("summary" in output && "risks" in output) return "risk-analysis";
  if ("objectives" in output && "test_areas" in output) return "test-plan";
  if ("coverage_assessment" in output && "gaps" in output) return "test-analysis";
  if ("test_suites" in output) return "test-design";
  return "unknown";
}

function renderRiskAnalysis(output: Record<string, unknown>): string {
  const lines: string[] = [];
  lines.push(String(output.summary));

  const risks = output.risks as Array<Record<string, string>> | undefined;
  if (risks && risks.length > 0) {
    lines.push("");
    lines.push("| ID | Severity | Category | Description | Mitigation |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const risk of risks) {
      lines.push(
        `| ${risk.id} | ${risk.severity} | ${risk.category} | ${risk.description} | ${risk.mitigation} |`,
      );
    }
  }

  return lines.join("\n");
}

function renderTestPlan(output: Record<string, unknown>): string {
  const lines: string[] = [];
  lines.push(String(output.objectives));

  const areas = output.test_areas as Array<Record<string, string>> | undefined;
  if (areas) {
    for (const area of areas) {
      lines.push("");
      lines.push(`### ${area.name}`);
      lines.push(area.description);
      if (area.priority) {
        lines.push(`**Priority**: ${area.priority}`);
      }
    }
  }

  return lines.join("\n");
}

function renderTestAnalysis(output: Record<string, unknown>): string {
  const lines: string[] = [];
  lines.push(String(output.coverage_assessment));

  const gaps = output.gaps as Array<Record<string, string>> | undefined;
  if (gaps && gaps.length > 0) {
    lines.push("");
    lines.push("### Gaps");
    lines.push("| Area | Description | Severity |");
    lines.push("| --- | --- | --- |");
    for (const gap of gaps) {
      lines.push(`| ${gap.area} | ${gap.description} | ${gap.severity} |`);
    }
  }

  const recommendations = output.recommendations as Array<Record<string, string>> | undefined;
  if (recommendations && recommendations.length > 0) {
    lines.push("");
    lines.push("### Recommendations");
    lines.push("| Title | Description | Priority |");
    lines.push("| --- | --- | --- |");
    for (const rec of recommendations) {
      lines.push(`| ${rec.title} | ${rec.description} | ${rec.priority} |`);
    }
  }

  return lines.join("\n");
}

function renderTestDesign(output: Record<string, unknown>): string {
  const lines: string[] = [];
  const suites = output.test_suites as Array<Record<string, unknown>> | undefined;

  if (suites) {
    for (const suite of suites) {
      lines.push(`### ${suite.name}`);

      const cases = suite.test_cases as Array<Record<string, unknown>> | undefined;
      if (cases) {
        for (const tc of cases) {
          lines.push("");
          lines.push(`#### ${tc.name}`);
          if (tc.preconditions) {
            lines.push(`**Preconditions**: ${tc.preconditions}`);
          }

          const steps = tc.steps as string[] | undefined;
          if (steps) {
            lines.push("");
            for (let i = 0; i < steps.length; i++) {
              lines.push(`${i + 1}. ${steps[i]}`);
            }
          }

          if (tc.expected_result) {
            lines.push("");
            lines.push(`**Expected Result**: ${tc.expected_result}`);
          }
        }
      }
    }
  }

  return lines.join("\n");
}

function renderJsonFallback(output: Record<string, unknown>): string {
  return `\`\`\`json\n${JSON.stringify(output, null, 2)}\n\`\`\``;
}
